name: Deploy iOS to Production
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: "Release Notes"
        required: true
        default: "Initial Release"
      groups:
        description: "TestFlight Tester Groups"
        required: false
jobs:
  deployIOSProduction:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: "stable"
          cache: true
        id: flutter
      - name: Accept Xcode License
        run: sudo xcodebuild -license accept
      - name: Get Packages
        run: flutter pub get
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: false
          working-directory: ios

      - name: Install Ruby gems
        working-directory: ios
        run: bundle install

      - name: Build and Deploy to TestFlight
        working-directory: ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          bundle exec fastlane ios production \
            release_notes:"${{ github.event.inputs.release_notes }}" \
            groups:"${{ github.event.inputs.groups }}"

